name: refcue_app
description: RefCue's app mainly made for referees to help them prepare for their exams, later on it will help them with all of their carrier of the football referee

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository
  animated_theme_switcher: ^2.0.0-nullsafety.0
  bloc: ^7.0.0-nullsafety.3
  cloud_firestore: ^1.0.1
  equatable: ^2.0.0
  firebase_storage: ^8.0.0
  flare_flutter: ^3.0.0-nullsafety.0
  auth_buttons: ^1.0.0
<<<<<<< HEAD
  flutter_bloc: ^6.1.1
  flutter_screenutil: ^3.2.0
  formz: ^0.3.2
  flutter_svg: ^0.19.3
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+21
  delayed_display: ^1.1.0
  cached_network_image: ^2.5.0
  line_awesome_flutter: ^1.0.1
  meta: ^1.1.8
  pedantic: ^1.9.0
  shared_preferences: ^0.5.12+4
=======
  flutter_bloc: ^7.0.0-nullsafety.5
  flutter_screenutil: ^5.0.0-nullsafety.9
  font_awesome_flutter: ^9.0.0-nullsafety
  formz: ^0.4.0-nullsafety.0
  flutter_svg: ^0.21.0-nullsafety.0
  image_cropper: ^1.4.0
  image_picker: ^0.7.2+1
  cached_network_image: ^3.0.0-nullsafety
  line_awesome_flutter: ^1.1.0-nullsafety
  meta: ^1.3.0
  pedantic: ^1.11.0
  shared_preferences: ^2.0.4
>>>>>>> 4ce715fdb0b421b78e44186433f6c5cc46e3fe48

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0-nullsafety.5
  mockito: ^5.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/flare/
    - assets/images/
    - assets/icons/
    - assets/icons/article_icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Montserrat-MediumItalic.ttf
          style: italic
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-MediumItalic.ttf
          style: italic
