name: authentication_repository
description: Dart package which manages the authentication domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.0
  firebase_auth: ^1.1.3
  firebase_core: ^1.1.0
  cloud_firestore: ^2.0.0
  google_sign_in: ^5.0.2
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.7
